### ISSUE TITLE
Co2 Value always 0

### ISSUE THREAD

**Issue by MartinNPN** [crossk3/EnvironmentalMonitorHub#9]
Hello, 
see: https://github.com/crossk3/EnvironmentalMonitorHub/blob/2bffafb648914b956d6eb09b06a9961c345e9074/Microprocessor/Libraries/SM-uart/AASv1.5_01L_T67xx/AASv1.5_01L_T67xx.ino#L195

there is a typo, meant is a comparison `==`

**Comment by crossk3** [comment]
You're correct, thank you Martin!

**Comment by MartinNPN** [comment]
No Problem.
